### ISSUE TITLE
Consider matching "My preferred boot order" with "Edit EEPROM" code

### ISSUE THREAD

**Issue by irq5dma1** [literatesnow/pi-5-archlinux-arm-encrypted-root#1]
Hi! Thank you for the guide, really helpful!

I noticed that, in the "Install" section, it is mentioned that the author's preferred boot order is `0xf461` (SD Card -> NVMe -> USB), but the code in the "Edit EEPROM:" code block uses `0xf416` (NVMe-> SD Card -> USB).

When following the guide, I didn't spot the difference, using the order in the "Edit EEPROM:" code block, and then wondering why the device was not booting from the SD Card when I needed to boot Raspberry OS for recovery.

I would suggest matching both boot order strings, as I agree that the `0xf461` is pretty convenient for most use cases, and would be more consistent with the guide.

**Comment by literatesnow** [comment]
Hey, glad you liked the guide! Thanks for spotting the mistake.
